### ISSUE TITLE
new interface request: hook function for Including/exlcuding folders/files

### ISSUE THREAD

**Issue by zzs213** [earnestt1234/seedir#1]
new par for seedir(), which would be a func, It determine whether the dir/file should be print out. like this:
```python
def is_print(path):
    if is_a_git_repos_dir(path):
        return True
    else:
        return False
sd.seedir(root_dir, func=is_print)
```

**Comment by earnestt1234** [comment]
@zzs213 thanks for the input - sounds like a good feature.  Will add in small update soon

**Comment by earnestt1234** [comment]
@zzs213 Added to [0.1.2](https://github.com/earnestt1234/seedir/releases/tag/v0.1.2) as a `mask` parameter.
