### ISSUE TITLE
How to only list folders, and exclude all files?

### ISSUE THREAD

**Issue by JamesO2x** [earnestt1234/seedir#11]
I can't seem to figure it out. The documentation mentions how to exclude specific files or folders, but not any way to exclude all files and just print folders only.

Am I missing something basic here?

EDIT: Oh my god, I spent like 20 minutes trying to figure this out, and as soon as I posted this issue I figured it out right after. :P 

I was trying to put regex into the `exclude_files=` argument, but I missed the part in the docs that mentioned I specifically had to also add the `regex=True` argument. So that's why my regex wasn't working.

Anyway, the solution I found was adding `exclude_files='.*\.*$', regex=True,` -- This seems to exclude all files. Thanks for this awesome tool, its really useful!

**Comment by JamesO2x** [comment]
I forgot to include the `regex=True` argument. @_@

**Comment by earnestt1234** [comment]
I will add some notes to make this more clear in the docs - glad it ended up working!  

For reference, other non-regex options would be `inclde_files=''` or `mask=lambda x : os.path.isdir(x)` 😁

**Comment by JamesO2x** [comment]
Thanks! Yeah making it more explicitly clear that the `regex=true` needs to be added for regex to work would be great.

And to be clear, are you saying that adding `include_files=''` would actually _exclude_ all files from the list? Instinctively I tried using `exclude_files=''` first, with my logic being that a blank value would exclude all files. But I think I was misunderstanding how that feature works.

But if `include_files=''` also removes all files from the list, that would be much simpler than my regex solution.

So if I am understanding the logic of how these arguments work, the `include_files` argument will **only** add the included files in the output list, correct? So a value of `include_files="readme.txt"` would exclude _any file_ that isn't exactly named `readme.txt`?

Then following that logic, a blank value of `include_files=''` would essentially only include files with a totally empty filename (which is impossible) so therefore it includes no files in the list.

That makes perfect sense.

I think when I was first trying to figure this out, my brain got attached to the word/concept of "exclude" because in my own words I wanted to "exclude all files" so I overlooked the "include" argument.

I just wanted to explain my thought process. I don't have any issue with the code, it makes perfect sense now. I think my brain was just tired when I was reading the documentation.

**Comment by earnestt1234** [comment]
Yes you got it!  E.g. `include_files` is indicating the names of files you explicitly want to include in the tree (either by name literally or via a regex pattern).  Maybe `included_files` would be a better name.  I get the expectation that you could do something like `exclude_files=True` to exclude files, but that is not how it has been implemented.

**Comment by earnestt1234** [comment]
Including one more note for (personal) reference.  Exclusion is prioritized over inclusion, so if an item is captured by both the inclusion and exclusion terms, it will be excluded.  I think I had actually intended the opposite (so that you could make exceptions to your exclusions) but I have verified that currently this is not possible.  The code for handling the inclusion/exclusion is relatively old, and very convoluted!  I definitely plan to clean this up, and perhaps I will alter the handling of conflicting include/exclude options.

**Comment by JamesO2x** [comment]
Yeah I actually did try doing 'exclude_files=True' at first, before looking over the docs again. I think your suggestion for using the wording 'excluded_files=' instead of 'exclude_file=' is probably a good idea. Its a small change, but the meaning is much more clear.
