### ISSUE TITLE
feature request: command line usage

### ISSUE THREAD

**Issue by cjw296** [earnestt1234/seedir#22]
It'd be great to be able to use this from the command line, eg:

```bash
python -m seedir /some/path
```

Would you be up for a PR and a release that implemented this?

**Comment by earnestt1234** [comment]
Good news - this already is a thing!  Provided you have seedir installed, try calling from your terminal:

```bash
seedir -h
```
You should get the help text.

[The CLI module is here](https://github.com/earnestt1234/seedir/blob/master/seedir/command_line.py) - you could also call `python -m seedir.command_line` but the pip installation should provide an entry point using just `seedir`.

Let me know if this is what your were looking for?  I can add some pointers to this in the documentation.

**Comment by cjw296** [comment]
Ah, right, how would you feel about making this work as well?

```python
$ python -m seedir --help
python: No module named seedir.__main__; 'seedir' is a package and cannot be directly executed
```

**Comment by earnestt1234** [comment]
That sounds good to me!  I guess that would just involve calling `seedir.command_line.main()` when `seedir.__init__.py` is ran as a script?

Still down to make a PR for that?

**Comment by J535D165** [comment]
Basically, it is only renaming a file, see #23. I fixed another small issue with the imports as well.

**Comment by earnestt1234** [comment]
even better!  Thanks

**Comment by cjw296** [comment]
Fantastic, thanks both!
