### ISSUE TITLE
[Feature requests] How to ignore error like permission denied.

### ISSUE THREAD

**Issue by ramwin** [earnestt1234/seedir#28]
compare to tree
![image](https://github.com/earnestt1234/seedir/assets/17930851/4b924493-b524-45b2-aff3-e567cb71d8b3)

![image](https://github.com/earnestt1234/seedir/assets/17930851/82d32d52-3713-483b-9ddd-a3c7d8f43a6c)

How about add a parameter like `errors="ignore"`?

**Comment by earnestt1234** [comment]
This functionality has been added in [version 0.5.0](https://github.com/earnestt1234/seedir/releases).  Relevant changes are in 61de607f1e740424e9ca2070dd705cfaaac02d15 and 83a6b07c2d95ee1908addd278f19522d0edd4cdb.

Two new parameters associated with this change are `acceptable_listdir_errors` (what errors are okay to be ignored) and `denied_string` (what string token to add to folders that can't be accessed).

Example:

```python
>>> import seedir
>>> seedir.seedir('/Users/admin/', depthlimit=2)
admin/
├─Music/ [ACCESS DENIED]
├─.Box_UIServer
├─.CFUserTextEncoding
├─Pictures/ [ACCESS DENIED]
├─Desktop/ [ACCESS DENIED]
├─Library/ [ACCESS DENIED]
├─Public/
│ ├─.localized
│ └─Drop Box/ [ACCESS DENIED]
├─Movies/ [ACCESS DENIED]
├─.Box_EngineServer
├─Documents/ [ACCESS DENIED]
└─Downloads/ [ACCESS DENIED]

```
